const timelineEvents = [
{year: "1600",
    title: "The East India Company is Born",
    tag: "Beginning",
    short: "A group of London merchants get a royal charter from Queen Elizabeth I to trade with Asia. This tiny trading company will one day rule most of India.",
    details: "On 31st December 1600, a company called the East India Company was given permission by the Queen to trade with countries in the east. At first it was only about spices, silk and cotton. Nobody at that point thought this trading company would end up controlling a huge country like India. This was basically the seed of everything that happened next.",
    image: "https://cdn.britannica.com/06/178206-050-584A8E02/East-India-Company-House-headquarters-England-London.jpg"},

{ year: "1608",
    title: "First English Ship Reaches Surat",
    tag: "Arrival",
    short: "Captain William Hawkins lands at Surat on the ship 'Hector'. This is the first real English footstep on Indian soil.",
    details: "The ship Hector arrived at the port of Surat in Gujarat. Captain William Hawkins later travelled all the way to the Mughal court of Emperor Jahangir to ask for trading permission. It took a few years, but eventually the English were allowed to set up a small trading post. This was step one of a very long process.",
    image: "https://lh7-rt.googleusercontent.com/docsz/AD_4nXdZGWqx-zPc0lco9fcXUUuFbFG3xlKIM7i4pOXGOnjENmsT14fkcAUbOK0ZERLyWrCQ1UvDak-eFlv6VBgJ6THvmfj8IKDSqrcMjtRXqkXL2MNvdvg8JzZZ9Nz7s7NxcPsrLRk02fpUexVgJCj3Ec3-Yxw?key=eDHw3NTYD28NW_3U11lOBg", },

{ year: "1757",
    title: "Battle of Plassey",
    tag: "Turning Point",
    short: "Robert Clive defeats Nawab Siraj-ud-Daulah with the help of betrayal from within (Mir Jafar). The Company now starts becoming a political power, not just a trading one.",
    details: "This battle is usually seen as the real starting point of British political control in India. It wasn't even a very big battle in terms of fighting, a lot of it was decided by Mir Jafar (the Nawab's own commander) secretly siding with the British. After this win, the Company placed their own puppet ruler and slowly began controlling Bengal's revenue and administration.",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Lord_Clive_meeting_with_Mir_Jafar_after_the_Battle_of_Plassey.jpg" },

{ year: "1764",
title: "Battle of Buxar",
tag: "Expansion",
short: "The Company defeats a combined army of the Nawab of Awadh, the Mughal Emperor and the Nawab of Bengal. This gets them the 'Diwani' rights - basically full tax collecting power.",
details: "After Buxar, the Treaty of Allahabad (1765) gave the East India Company the Diwani of Bengal, Bihar and Odisha. This meant the Company could now legally collect taxes from these regions. This is the point where the line between 'trading company' and 'ruling government' basically disappeared.",
image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Gr5RmardqepM2omtn6La-CT8YDiGP3dawpFe22Wtdy_w9XJYFb1XCww&s=10" },

{ year: "1799",
    title: "Fall of Tipu Sultan (Mysore)",
    tag: "Resistance",
    short: "Tipu Sultan, the 'Tiger of Mysore', dies fighting the British at the Battle of Seringapatam. One of the strongest early resistances to British expansion ends.",
    details: "Tipu Sultan had fought the British across four Anglo-Mysore Wars and was one of the few rulers who genuinely troubled the East India Company militarily. His death in 1799 defending his fort removed one of the last major regional powers that could stand up to British expansion in the south.",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c9/Tipu_death.jpg" },

{ year: "1817",
title: "Third Anglo-Maratha War",
    tag: "Resistance",
    short: "The British finally crush the powerful Maratha Confederacy, ending the last major Indian power that could challenge Company rule on a large scale.",
    details: "The Marathas had fought the British in three separate wars over decades. This final war broke up the Maratha Confederacy for good and left the East India Company as the dominant power across almost all of India, with only a few princely states left semi-independent.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaDKmQz8_FBAbVgvv9r3h8wbNK6F9fpvGMmQ2fLb1WgA&s" },

{ year: "1857",
title: "The Great Revolt",
tag: "Rebellion",
    short: "Also called the Sepoy Mutiny or India's First War of Independence. It starts in Meerut and spreads fast across North India.",
    details: "Indian soldiers (sepoys) working for the Company rebelled, partly because of the new cartridges rumoured to be greased with cow and pig fat, but really the anger had been building up for years over land taxes, harsh rule and disrespect of local customs. Leaders like Mangal Pandey, Rani Lakshmibai, Bahadur Shah Zafar and Tantia Tope became symbols of this uprising. It was crushed eventually, but it shook the British badly.",
    image: "https://bharatpunj.com/wp-content/uploads/2023/03/1857-Rebellion.jpg"},

{ year: "1858",
title: "Crown Rule Begins",
  tag: "Shift of Power",
    short: "After the revolt, the British Government takes direct control of India from the East India Company. This period is called the British Raj.",
    details: "The Government of India Act 1858 dissolved the East India Company's rule and transferred all power directly to the British Crown, under Queen Victoria. A Viceroy was now appointed to run India on behalf of the Queen. This started the official 'British Raj' period which lasted until 1947.",
    image: "https://c8.alamy.com/comp/P84D87/the-proclamation-of-queen-victoria-as-sovereign-of-india-by-lord-canning-at-allahabad-uttar-pradesh-on-1-november-1858-under-the-government-of-india-act-1858-following-the-indian-rebellion-of-1857-P84D87.jpg"},

{ year: "1885",
title: "Indian National Congress is Formed",
tag: "Organising",
    short: "A.O. Hume along with Indian leaders start the Indian National Congress, which later becomes the main platform for the freedom movement.",
    details: "The INC started off pretty moderate, mostly asking the British for more Indian representation in government. Over time, as more leaders like Gokhale, Tilak, Gandhi and Nehru joined, it grew into the biggest and most important organisation pushing for full independence.",
image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHyaX_Po_gFPydaLksauPAUb7Z7ZXggKICwJ1kSzT7Ks5vho76fDWiKqc&s=10"},
  
{year: "1905",
title: "Partition of Bengal",
    tag: "Unrest",
    short: "Lord Curzon divides Bengal into two parts, officially for 'better administration' but really to split Hindus and Muslims. It backfires and unites people in protest instead.",
    details: "The partition led to huge protests and the birth of the Swadeshi Movement, where people boycotted British goods and started supporting Indian made products. The public anger was so strong that the British were forced to reverse the partition in 1911. This event really pushed the freedom movement into a more active phase.",
image: "https://cdn.prod.website-files.com/605048f161294e66292f01ff/6062d161521a700511eb11be_bengal_partition1-x402.jpg"},

{ year: "1906",
    title: "All India Muslim League is Founded",
    tag: "Organising",
    short: "Formed in Dhaka to represent the political interests of Muslims in India, this organisation later plays a huge role in the events leading up to 1947.",
    details: "The Muslim League started out focused on protecting Muslim rights within a British-ruled India, but over the decades, especially under Muhammad Ali Jinnah's leadership, its demands grew into a call for a separate nation, which eventually led to the creation of Pakistan alongside India's independence.",
image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/All_India_Muslim_League_Working_Committee_Lahore_1940.jpg/250px-All_India_Muslim_League_Working_Committee_Lahore_1940.jpg"},
{year: "1916",
    title: "Home Rule Movement",
tag: "Movement",
short: "Bal Gangadhar Tilak and Annie Besant separately launch Home Rule Leagues, demanding self-government for India within the British Empire.",
details: "Inspired by the Irish Home Rule movement, Tilak famously declared 'Swaraj is my birthright and I shall have it.' Annie Besant, an Irish-born activist, ran her own parallel Home Rule League. Together these movements spread the demand for self-rule to a much wider audience across India.",
image: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Bal_Gangadhar_Tilak_in_Madras_1917.jpg"},
  
{year: "1917",
    title: "Champaran Satyagraha",
    tag: "Movement",
    short: "Gandhi's very first big satyagraha (protest) on Indian soil, standing up for indigo farmers in Bihar being forced into unfair farming contracts.",
    details: "Before this, Gandhi was mostly known for his work in South Africa. Champaran was the movement that introduced his method of peaceful, non-violent resistance to India for the first time, and it worked - the British were forced to change the exploitative indigo farming system. This basically launched Gandhi's leadership in the Indian freedom struggle.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Gandhiji_and_Sub-Inspector_Qurban_Ali_in_Champaran_%281917%29.jpg/330px-Gandhiji_and_Sub-Inspector_Qurban_Ali_in_Champaran_%281917%29.jpg"},

{ year: "1919",
    title: "Jallianwala Bagh Massacre",
    tag: "Tragedy",
    short: "General Dyer orders troops to open fire on an unarmed crowd gathered in Amritsar. Hundreds die. This becomes a major turning point for the whole country's mood towards the British.",
    details: "People had gathered peacefully at Jallianwala Bagh in Amritsar, many just to celebrate the festival of Baisakhi, when General Reginald Dyer ordered soldiers to fire directly into the crowd without warning, with the only exit blocked. This event completely changed how Indians, including many who were previously loyal to the British, viewed colonial rule. It happened right after the harsh Rowlatt Act was passed, which had already angered the whole country.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoE3ylBtAHqFagu46-TD0TcUg45prKF606nlAygCkpWv_wSmlOE-Et2ew&s=10"},

  {year: "1920",
    title: "Non-Cooperation Movement",
    tag: "Mass Movement",
    short: "Mahatma Gandhi launches the first big nationwide movement, asking Indians to stop cooperating with British institutions - schools, courts, jobs, everything.",
    details: "This was the first time the freedom struggle became a true mass movement involving common people, not just educated elites. Gandhi's idea was simple - if Indians stop cooperating with British rule (leaving government jobs, boycotting British goods and institutions), the whole system would collapse on its own. It also merged with the Khilafat Movement, bringing Hindus and Muslims together on one platform.",
    image: "https://mediaindia.eu/wp-content/uploads/2020/02/770e2cbbbaff83e0eb734fc9919c5948-1200x675.jpeg"},

  {year: "1922",
    title: "Chauri Chaura Incident",
    tag: "Turning Point",
    short: "A violent clash between protestors and police in a small UP village leads Gandhi to suddenly call off the Non-Cooperation Movement.",
details: "A crowd of protestors set fire to a police station, killing several policemen. Gandhi, who strongly believed the movement had to stay non-violent, was so disturbed by this that he called off the entire Non-Cooperation Movement, even though it was gaining huge momentum. Many younger leaders were frustrated by this decision, but it stayed true to Gandhi's principles.",
image: "https://img.jagranjosh.com/images/2021/February/522021/Chauri-Chaura-Incident.jpg"},
  
{ year: "1928",
title: "Simon Commission Protests",
tag: "Unrest",
short: "The British send a commission to India with zero Indian members on it. Massive protests break out, and freedom fighter Lala Lajpat Rai is fatally injured during a lathi-charge.",
    details: "The Simon Commission was meant to review India's political situation, but the fact that it had no Indian representatives at all led to nationwide protests of 'Simon Go Back'. During one such protest in Lahore, Lala Lajpat Rai was badly injured by police and died a few weeks later, which further fuelled anger against British rule.",
    image: "https://cdn.britannica.com/93/270593-050-BF249625/Demonstration-in-Pune-India-against-British-colonial-rule-1928-Simon-Go-Back--banner-refers-to-the-Simon-Commission.jpg"},

{year: "1929",
    title: "Purna Swaraj Declaration",
    tag: "Milestone",
    short: "At the Lahore session, the Congress officially declares 'Purna Swaraj' (complete independence) as its goal, not just self-rule within the empire.",
    details: "Led by Jawaharlal Nehru as Congress president, this session raised the tricolour flag on the banks of the Ravi river and declared 26th January as 'Independence Day', to be observed every year until real independence was achieved. This is actually why 26th January was later chosen as the date for India's Republic Day.",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/fa/The_Indian_National_Congress_moves_toward_independence.cropped.jpg"},

{ year: "1930",
    title: "Dandi March (Salt Satyagraha)",
    tag: "Civil Disobedience",
    short: "Gandhi walks 240 miles to the coastal village of Dandi to make salt himself, breaking the British salt law as a symbol of peaceful resistance.",
    details: "The salt tax law made it illegal for Indians to make or sell salt, forcing them to buy it from the British at a tax. Gandhi picked this simple, everyday item to protest because it affected every single Indian, rich or poor. Thousands joined him on the march, and it kicked off the wider Civil Disobedience Movement across the country.",
    image: "https://s02.sgp1.cdn.digitaloceanspaces.com/article/136342-jqcylmoemj-1581405670.jpg"},

  {year: "1931",
    title: "Gandhi-Irwin Pact",
    tag: "Negotiation",
    short: "Gandhi agrees to call off the Civil Disobedience Movement in exchange for the release of political prisoners, and attends the Round Table Conference in London.",
    details: "This pact was a rare moment of the British Government treating Gandhi as an equal negotiating partner. Gandhi travelled to London for the Second Round Table Conference, but it didn't achieve much in real terms, and Civil Disobedience eventually started up again after he returned.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCB0CXwRYM1YLe5qB4AJMrQo8SyF6_zB7uAxcztKgx2NtbTqQyDDr_KsQp&s=10"},

  {year: "1942",
    title: "Quit India Movement",
    tag: "Final Push",
    short: "With the famous slogan 'Do or Die', Gandhi launches the final big movement demanding the British leave India immediately.",
    details: "By 1942, patience had run out. The Quit India Movement was a direct and clear demand for immediate independence, with Gandhi telling Indians to either free the country or die trying. The British responded by arresting almost the entire top leadership of the Congress overnight, but the movement had already lit a fire that couldn't really be put out anymore.",
    image: "https://images.firstpost.com/wp-content/uploads/2020/08/quit-india-movement_640.jpg?im=FitAndFill=(596,336)"},
  {year: "1943",
    title: "Azad Hind Fauj (INA) Under Subhas Chandra Bose",
    tag: "Armed Struggle",
    short: "Subhas Chandra Bose takes charge of the Indian National Army and forms a provisional government, fighting the British with outside military support during World War II.",
    details: "Unlike Gandhi's non-violent approach, Bose believed armed resistance was necessary and led the INA (made up largely of Indian prisoners of war and volunteers) into military campaigns against the British in the Northeast. Even though the INA didn't win militarily, the later trials of its soldiers back in India created massive public sympathy and anger against British rule.",
    image: "https://archive.siasat.com/wp-content/uploads/2018/04/DISCOURSE-2.jpg"},
  {year: "1946",
    title: "Royal Indian Navy Revolt",
    tag: "Rebellion",
    short: "Indian sailors of the Royal Indian Navy mutiny against British officers in Bombay, a sign that even the armed forces were no longer reliably loyal to the British.",
    details: "What started as a protest over poor food and discrimination on a single ship quickly spread to dozens of ships and shore establishments across the country, with sailors raising nationalist flags. This event convinced the British that holding onto India by force was no longer realistic, and it sped up the final talks for independence.",
    image: "https://timesofindia.indiatimes.com/blogs/wp-content/uploads/2017/05/thumbnail_rating-arrested.jpg"},

  {year: "1947",
    title: "India Gains Independence",
    tag: "Freedom",
    short: "At midnight on 15th August 1947, India becomes a free country. Jawaharlal Nehru delivers his famous 'Tryst with Destiny' speech. The joy comes along with the pain of Partition.",
    details: "After nearly 350 years since that first English ship, and decades of struggle, sacrifice and movements, India finally became independent on 15th August 1947. It was a bittersweet moment though, because the country was also partitioned into India and Pakistan, which caused one of the largest and most painful migrations in human history. Still, this day remains the proudest chapter of this whole timeline.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwOHbx08RPJd09xtgN-TA7x3lajXLjt6RVrNytuMIn3D_iODXU4oIA84w&s=10"},
  {year: "2022",
    title: "75 Years of Independence — Azadi Ka Amrit Mahotsav",
    tag: "Legacy",
    short: "India celebrates 75 years of independence, looking back at everything the country went through to get here, and everything it has built since.",
    details: "Marked as 'Azadi Ka Amrit Mahotsav', this milestone was celebrated across the country with events, cultural programs and the 'Har Ghar Tiranga' campaign, encouraging every household to fly the national flag. From a colony that fought for nearly 350 years to be free, to a growing independent nation on the world stage - this is where the story stands today, and it keeps being written.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIDF5fW4QgCR5lFf3f-ww_U24ylRPBlar1qQ9ktUk8BMshcxyQBnO1ApH7&s=10"}
];
